-- Reemplaza el ZONE_OPTIONS hardcodeado del cliente por una tabla real `zonas`,
-- tal como estaba previsto en el comentario de 20260815040000_activity_zona.sql.
-- Se mantienen los mismos id (1 = Tienda, 2 = Colegio) para no romper las
-- actividades ya creadas.

create table public.zonas (
  id integer generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

insert into public.zonas (id, name) values (1, 'Tienda'), (2, 'Colegio');

select setval(pg_get_serial_sequence('public.zonas', 'id'), (select max(id) from public.zonas));

alter table public.activities
  add constraint activities_zona_id_fkey foreign key (zona_id) references public.zonas (id);

alter table public.zonas enable row level security;

create policy "authenticated_full_access" on public.zonas
  for all to authenticated
  using (true)
  with check (true);
